fullname = input("Please input your full name : ")
gender = input("Input your Gender : ")
age = input("Input your Age : ")
status = input("Input your Status : ")
BirthMonth = input("Input your Birth Month : ")
BirthDay = input("Input your Birth Day : ")
BirthYear = input("Input your Birth Year : ")
religion = input("Input your Religion : ")
nationality = input("Input your Nationality : ")
fname = input("Input your Father's Name : ")
mname = input("Input your Mother's Name : ")
EmailAddress = input("Input your Email Address : ")
address = input("Input your Address : ")

print("\nHi, My name is",fullname,"\b, an",age,"year old",gender,"\b,",status,"\b, born on",BirthMonth, BirthDay, BirthYear,"\b, living in",address,"\b.\nI am a",nationality,"citizen and a",religion,"\b.\nMy father's name is",fname,"and my mother's name is",mname,"\b.\nYou can reach me through gmail at",EmailAddress)
